### PR TITLE
use noInterrtups() instead of the Atomic block?

### PR DESCRIPTION
**Pull request by Thomasrutgers**
I needed to do this to have it work on my Arduino Primo.

### CODE REVIEW

**Comment by Koepel** [comment]
The atomic block restores the state. The noInterrupts() and interrupts() do not. It is not the same.

Using the SoftwareWire in a situation where the interrupts should be off all the time is rare, but not unlikely, since the SoftwareWire might be chosen over the Wire library just because interrupts can stay off.

Will the Arduino Primo with nRF52 processor support the ATOMIC_BLOCK macro in the future ?

**Comment by stevemarple** [comment]
I think the `ATOMIC_BLOCK` block is AVR-specific.
@Thomasrutgers: is there an NRF equivalent macro that can be used. Better would be a generic libc equivalent but I'm not aware of one.

**Comment by Thomasrutgers** [comment]
Ok, I see.

**Comment by stevemarple** [comment]
@Thomasrutgers Does v1.1.0 compile for you?

**Comment by Thomasrutgers** [comment]
@stevemarple Yes, compiles! Haven't tested all of it, but the listdevices example is working.

**Pull request closed without merging**
